### PR TITLE
Issues #29 resolve

### LINKED ISSUE #29: Remove or fix `updated_at`
Currently taitan returns a field called `updated_at` which is set to the modification timestamp of the file, but that is the time taitan last pulled the repository, which is useless.

We should either remove the field or make it actually represent when the file last was modified (which could be useful to display in bawang).

I think we can get the actual update time by getting the date of the last commit that changed the given file.

### PR DESCRIPTION
**Pull request by k124k3n**
### Get commit time using go-git

closes #29

### CODE REVIEW

**Review by mathiasmagnusson — COMMENTED** [review]
Hi, and thank you for your contribution.

This is a repository that we use for our external and internal websites so not something to expect external contributions.

I must however ask if you've tried running the code as it does not have the correct path to neither the content repository or the given file to check the date for.

**Comment by k124k3n** [comment]
Sorry, i assume that `body.md` file is in `taitan` repository.

**Comment by k124k3n** [comment]
Which repository that `body.md` file belong?

**Comment by k124k3n** [comment]
For the given file, current code is referring to `bodyPath.ModTime()`, which is `body.md`'s ModTime().

**Comment by k124k3n** [comment]
Actually, we can check the commit time without specifying `repoPath` with something like:
``` go
exec.Command("git", "log", "--format=%at", "--", filePath)
```

But, is it safe enough to do raw commands?

**Comment by mathiasmagnusson** [comment]
> Sorry, i assume that `body.md` file is in `taitan` repository.
> May I knew which repository that body.md file belong?

I guess it's not very clear (i think it's only partially referenced in `.env.example`), but the two content repositories we use taitan for is https://github.com/datasektionen/bawang-content and https://github.com/datasektionen/styrdokument. And there are loads of `body.md`-files in them.

> [...] But, is it safe enough to do raw bash commands?
Go's `exec.Command` doesn't use bash, it executes the program (git in the given case) directly, so references to environment variables and other bash-stuff would not do anything. So yes that's definitely safe! It is also what we do to clone the repository.

From some quick testing it also seems like the git cli is way faster than the go-git library, but I didn't do it thoroughly at all.

---

You can get the api running correctly by copying `.env.example` to `.env` and filling anything into the token, as github does not seem to check it since the content repository is public.

**Comment by k124k3n** [comment]
> [...] Go's exec.Command doesn't use bash
Thank you for the new insight.

I'll try to get the api running

**Comment by k124k3n** [comment]
I got it. `taitan` finds all body.md in `$CONTENT_URL`. It means the file is not in local, it's on the internet.

**Comment by k124k3n** [comment]
Wait, change to `stripPrefix` instead.

**Comment by k124k3n** [comment]
Working on `_test.go`

**Comment by k124k3n** [comment]
There's different `directory` style between Linux and Windows. Working on it.

**Comment by k124k3n** [comment]
Should I let this to platform-dependent on `GOOS='Linux'`?

**Comment by mathiasmagnusson** [comment]
It might work on other platforms, but in production we run it on linux and that is what most people are running anyway (sometimes that's because of docker but still counts), so windows is not important to us.

Anyways, thanks very much for your contribution!

**Comment by k124k3n** [comment]
Thanks for guiding me through. Sorry for mistakes at the beginning. 

See you next time.

**Pull request merged**
